version: "3.8"

services:
  frontend_dev:
    build:
      dockerfile: ./frontend/Dockerfile.dev
    environment:
      - VITE_BASE_API_URL=http://0.0.0.0:8080
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    user: 1000:1000

  backend_dev:
    build:
      dockerfile: ./backend/Dockerfile.dev
    environment:
      - DEBUG=true
      - LOG_LEVEL=info

      - HOST=0.0.0.0
      - PORT=8080

      - DATABASE_URL=postgresql://pg:5432/twitter_clone?user=user&password=password

      - UPLOADS_DIR_PATH=/uploads/

      - ENCODED_SESSION_HASH_KEY=wbuNF/yrhZ6JDZw3yX7YZOMT+sk+z+xYf+IRmYJE2oMPgXlmlbYjexo5VKLGbVkZAYdnxxgdP5uu0jgNjPzAfA==
      - ENCODED_SESSION_BLOCK_KEY=OW655QMHxqFIrEMzPtI5Y8ZLpskzdEevudwyLmE/lOg=

      - JWT_SECRET_KEY=secret
    volumes:
      - ./backend:/backend
    ports:
      - 8080:8080
    links:
      - pg
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:12
    environment:
      - POSTGRES_DB=twitter_clone
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d twitter_clone" ]
      interval: 5s
      timeout: 5s
      retries: 5
