debug: true
log_level: info

host: 0.0.0.0
port: 8080

# database_url: postgresql://0.0.0.0:5432/twitter_clone?user=user&password=password
database_url: postgresql://pg:5432/twitter_clone?user=user&password=password
